version: '3.8'

services:
  scraper:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: driving_school_scraper
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=driving_schools
      - DB_USER=scraper_user
      - DB_PASSWORD=${DB_PASSWORD}
      - API_KEY=${API_KEY}
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    depends_on:
      - db
    command: ["python", "cloud_deployment/incremental_scraper.py"]

  db:
    image: postgres:15
    container_name: driving_schools_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=driving_schools
      - POSTGRES_USER=scraper_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Removed public port exposure for security - database only accessible within Docker network

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: driving_schools_api
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://scraper_user:${DB_PASSWORD}@db:5432/driving_schools
      - API_KEY=${API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "127.0.0.1:8080:80"  # Only accessible from localhost for security
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

# nginx:
#   image: nginx:alpine
#   container_name: nginx_proxy
#   restart: unless-stopped
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#     - ./ssl:/etc/nginx/ssl
#   depends_on:
#     - api

volumes:
  postgres_data:
  pgadmin_data:
